# Generated by Django 3.0.2 on 2020-01-27 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BioTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=0, max_length=20)),
                ('test_id', models.CharField(max_length=7)),
                ('qn', models.TextField(max_length=300)),
                ('a1', models.TextField(max_length=300)),
                ('a2', models.TextField(max_length=300)),
                ('a3', models.TextField(max_length=300)),
                ('a4', models.TextField(max_length=300)),
                ('ans', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ChemTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=0, max_length=20)),
                ('test_id', models.CharField(max_length=7)),
                ('qn', models.TextField(max_length=300)),
                ('a1', models.TextField(max_length=300)),
                ('a2', models.TextField(max_length=300)),
                ('a3', models.TextField(max_length=300)),
                ('a4', models.TextField(max_length=300)),
                ('ans', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CseTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=0, max_length=20)),
                ('test_id', models.CharField(max_length=7)),
                ('qn', models.TextField(max_length=300)),
                ('a1', models.TextField(max_length=300)),
                ('a2', models.TextField(max_length=300)),
                ('a3', models.TextField(max_length=300)),
                ('a4', models.TextField(max_length=300)),
                ('ans', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='LoginDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('user_id', models.CharField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MathTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=0, max_length=20)),
                ('test_id', models.CharField(max_length=7)),
                ('qn', models.TextField(max_length=300)),
                ('a1', models.TextField(max_length=300)),
                ('a2', models.TextField(max_length=300)),
                ('a3', models.TextField(max_length=300)),
                ('a4', models.TextField(max_length=300)),
                ('ans', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PhyTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=0, max_length=20)),
                ('test_id', models.CharField(max_length=7)),
                ('qn', models.TextField(max_length=300)),
                ('a1', models.TextField(max_length=300)),
                ('a2', models.TextField(max_length=300)),
                ('a3', models.TextField(max_length=300)),
                ('a4', models.TextField(max_length=300)),
                ('ans', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('SNo', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phno', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('date', models.DateField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherDetails',
            fields=[
                ('TNo', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phno', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('date', models.DateField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=10)),
                ('answer_1', models.CharField(max_length=2)),
                ('answer_2', models.CharField(max_length=2)),
                ('answer_3', models.CharField(max_length=2)),
                ('answer_4', models.CharField(max_length=2)),
                ('answer_5', models.CharField(max_length=2)),
                ('SNo', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='OnlineTest.StudentDetails')),
                ('TNo', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='OnlineTest.TeacherDetails')),
                ('test_code', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='OnlineTest.CseTest')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phy', models.CharField(blank=True, max_length=3)),
                ('chem', models.CharField(blank=True, max_length=3)),
                ('math', models.CharField(blank=True, max_length=3)),
                ('bio', models.CharField(blank=True, max_length=3)),
                ('cse', models.CharField(blank=True, max_length=3)),
                ('teacherdetails', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='OnlineTest.TeacherDetails')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherLoginDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=0, max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('teacherdetails', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='OnlineTest.TeacherDetails')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phy', models.CharField(blank=True, max_length=3)),
                ('chem', models.CharField(blank=True, max_length=3)),
                ('math', models.CharField(blank=True, max_length=3)),
                ('bio', models.CharField(blank=True, max_length=3)),
                ('cse', models.CharField(blank=True, max_length=3)),
                ('studentdetails', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='OnlineTest.StudentDetails')),
            ],
        ),
        migrations.CreateModel(
            name='StudentLoginDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=0, max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('studentdetails', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='OnlineTest.StudentDetails')),
            ],
        ),
    ]
