# Generated by Django 3.0.2 on 2020-01-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineTest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biotest',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chemtest',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='csetest',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mathtest',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phytest',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
