# Generated by Django 3.0.2 on 2020-01-28 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineTest', '0003_auto_20200127_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='answer_1',
            new_name='a1',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='answer_3',
            new_name='a2',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='answer_2',
            new_name='a3',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='answer_4',
            new_name='a4',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='answer_5',
            new_name='a5',
        ),
        migrations.RemoveField(
            model_name='test',
            name='SNo',
        ),
        migrations.RemoveField(
            model_name='test',
            name='TNo',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test_code',
        ),
        migrations.AddField(
            model_name='test',
            name='studentdetails',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='OnlineTest.StudentDetails'),
        ),
        migrations.AddField(
            model_name='test',
            name='teacherdetails',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='OnlineTest.TeacherDetails'),
        ),
        migrations.AddField(
            model_name='test',
            name='test_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='OnlineTest.CseTest'),
        ),
        migrations.AlterField(
            model_name='studentsubjects',
            name='bio',
            field=models.CharField(blank=True, default='off', max_length=3),
        ),
        migrations.AlterField(
            model_name='studentsubjects',
            name='chem',
            field=models.CharField(blank=True, default='off', max_length=3),
        ),
        migrations.AlterField(
            model_name='studentsubjects',
            name='cse',
            field=models.CharField(blank=True, default='off', max_length=3),
        ),
        migrations.AlterField(
            model_name='studentsubjects',
            name='math',
            field=models.CharField(blank=True, default='off', max_length=3),
        ),
        migrations.AlterField(
            model_name='studentsubjects',
            name='phy',
            field=models.CharField(blank=True, default='off', max_length=3),
        ),
    ]
