# Generated by Django 3.0.2 on 2020-01-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineTest', '0005_auto_20200128_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
