# Generated by Django 3.0.2 on 2020-01-31 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineTest', '0007_anstrial_qnstrial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anstrial',
            old_name='answe',
            new_name='answer',
        ),
    ]
