# Generated by Django 3.0.2 on 2020-01-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineTest', '0008_auto_20200131_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='anstrial',
            name='marks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
