# Generated by Django 3.0.2 on 2020-01-31 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineTest', '0009_anstrial_marks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnsTrial',
        ),
        migrations.DeleteModel(
            name='QnsTrial',
        ),
    ]
